hyperskill_project:
  id: 114
  ide_files: https://cogniterra.org/media/attachments/lesson/25009/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
  - id: 619
    step: 10239
    is_completed: true
  - id: 620
    step: 10240
    is_completed: false
  - id: 621
    step: 10241
    is_completed: false
  - id: 622
    step: 10242
    is_completed: false
  - id: 623
    step: 10243
    is_completed: false
  - id: 624
    step: 10244
    is_completed: false
topics:
  0:
    - title: Introduction to Python
      theory_id: 47352
    - title: Multi-line programs
      theory_id: 47555
    - title: "PEP 8: Coding style guide"
      theory_id: 47499
    - title: Taking user's input
      theory_id: 47680
    - title: Program with numbers
      theory_id: 47734
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: PyCharm basics
      theory_id: 6193
    - title: Elif statement
      theory_id: 5926
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Debugging Python applications in PyCharm
      theory_id: 19163
    - title: Basic data types
      theory_id: 47516
    - title: Variables
      theory_id: 47536
    - title: "Integer arithmetic: basic operations"
      theory_id: 47564
    - title: "Integer arithmetic: special operations"
      theory_id: 47917
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Declaring functions
      theory_id: 5900
    - title: "Working with strings: basic methods"
      theory_id: 6842
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: Escape sequences
      theory_id: 7130
    - title: Splitting strings and joining lists
      theory_id: 6972
    - title: Regular expression
      theory_id: 7580
  1:
    - title: Computer algorithms
      theory_id: 16547
    - title: While loop
      theory_id: 5940
    - title: Algorithms in Python
      theory_id: 7316
    - title: Recursion basics
      theory_id: 5984
    - title: Indexes
      theory_id: 6189
    - title: Functional decomposition
      theory_id: 9571
    - title: List comprehension
      theory_id: 6315
    - title: Slicing
      theory_id: 6177
    - title: Recursion in Python
      theory_id: 7665
  2:
    - title: Immutability
      theory_id: 7929
    - title: Comments
      theory_id: 6081
    - title: What is object-oriented programming
      theory_id: 3614
    - title: "Loop control: break, continue, pass"
      theory_id: 6302
    - title: Avoiding bad comments
      theory_id: 6440
    - title: Identity testing
      theory_id: 8077
    - title: Objects in Python
      theory_id: 9262
    - title: "Function, arguments and parameters"
      theory_id: 7248
    - title: Operations with list
      theory_id: 6031
    - title: Default arguments
      theory_id: 10295
    - title: Tuple
      theory_id: 7462
    - title: Args
      theory_id: 8560
    - title: Dictionary
      theory_id: 6481
    - title: Dictionary methods
      theory_id: 9008
    - title: Operations with dictionary
      theory_id: 11096
    - title: Kwargs
      theory_id: 9544
  3:
    - title: Importing modules
      theory_id: 6019
    - title: Creating modules
      theory_id: 6057
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Methods
      theory_id: 6931
    - title: Docstrings
      theory_id: 11869
    - title: Global vs local. Scopes
      theory_id: 6322
    - title: String formatting
      theory_id: 6037
    - title: Function annotations
      theory_id: 15664
  5:
    - title: Pydoc
      theory_id: 18505
